apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forum-frontend
  template:
    metadata:
      labels:
        app: forum-frontend
    spec:
      containers:
        - name: frontend
          image: nelove288/forum-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: forum-frontend
spec:
  selector:
    app: forum-frontend
  ports:
    - port: 80
      targetPort: 80
