apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forum-ingress
spec:
  rules:
    - host: forum.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: forum-frontend
                port:
                  number: 80
