apiVersion: v1
kind: Service
metadata:
  name: forum-frontend-service
spec:
  type: NodePort
  selector:
    app: forum-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # 원하는 포트로 설정 (30000~32767 범위)
